---
sudo: false
addons:
  apt:
    packages: []
  coverity_scan:
    project:
      description: Build submitted via Travis CI
      name: maxmind/minfraud-api-java
    notification_email: dev-ci@maxmind.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: .*coverity.*
language: java
matrix:
  include:
    - jdk: openjdk7
    - jdk: openjdk8
    - jdk: openjdk11
      env: RUN_SNYK=true
    - jdk: openjdk12
    - jdk: openjdk-ea
    - jdk: oraclejdk8
    - jdk: oraclejdk11
  allow_failures:
    - jdk: openjdk-ea
env:
  global:
    - secure: ExeU8coyJzkKuZwLjeVUl8y0PgEWQ7xl3JBFcJcYyweVQbid0Av2ZDEdOrJDTiT7Vb7/Gmny0sUOCyclPDOH8RS+0ENerhA/JDgsrU8KfSDLvPDjBXPX7sEnLVbCmM0SESjRNZ8apVgZexcbODQRfv6FRgpue0TomVb35c/Jdeu577DdEhXUr3PYbgluKhayZlRoJgdEYRKGolbstlkA4Zx6hUDoq2+Wzt782bQ7SOZD/Xi4VG/X7T8sUNjbg8JpxoN2rf/1Jsa3+HGVIaArda6KQu03iNQ/nqgRMB5Q9lOMXIwoLjEFVWHrJd7mBaHaHI0AJnCem/DP7amTsyv6vjgXHTHlPS2Cf6X/127ljry1+oOwLLe7o3ofsZkKB1+0+VhalHXFM60KHwAdsgYP1wS2uP8ITfNG3GGkVp8boS586Kkd0LfGxXEnqhiKYlJlChqlCJTnHwzo/eIQGymGcAxLXQo5vYiK/CwkXyewIbeR+u1yRuXTudwXE6bQaDUTQhl4EPut4MDlovrE61quk3OtBLtS085k9gggU9M0Av8VX+LXdPke+39Z/fAFjdVoGSOkmvAKDftlaqR79TQ/ALN/dhl9d9umVd1xcxig+uQxrXR+HSdXz2ISNnacEP0ejrbOYLJbb5ph7ftZmkC/fsk8BcSt7eAncHXbASJeaM4=
    - secure: pYYfFKf/HaJsj7Q/2QjUPcvVegq6kZLHW2pJag85eE3UcMB5IvxtxuJudIyDSQb8T+GMYwIwypTGuWYj26xepsXTJbVkRwQuQKnAIZojCn+VI3x+Mif+rZtUwwXY/uxSs9FHLrdE3U+RNtRLX4IlzJt5Kpaaqit8jBcu0BT4yCpxURarTL0xiCzwAGkRDRq42lnp84ldVI+RbECMtOmrJuHePOsAUo3egn/6j0lnWlZdopvggECKue/7rRJZwClnaC5Ckp7A8d7lVFOqrthUg4aaCdLJqfnlHWvdrWsvg2ce0Tnk7doi9fEJYpBzg7vR1aBOjz7pDonWtRUH7g+oxkRSNwSU7TZpw10ukEjK61OMDqkzxgv377tzoDs5cmuzDn0BBfNWJIYoBZ1VqFsHNROcCyt41Vg3zOrZtZJyps4oBSpWQdjBJui+L8gQehvwbx5s/H1hEyIXMOdspf/pzNcw8rFFX4Z5SI0WYj2+p1lJpiYcBJFR4ksi+OHQ8Wkcvsu77dE9SKBuPBx9ZtOR30J4jwiVHmnPGqAgB79aRc4W5skpSFHtYSSkl2eQCTh1tBuw6lVDbWdY5RlY7xCYYqsSSzfGe6ERs6Jg2RabUf/VP7AIY6Z9s6c/XfdtQ18wnCmie7phs/exwaSULFaxFGYHVuwXSthZzFuN2CItrmY=
before_install:
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then sudo apt-get install -y nodejs; fi"
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then npm install -g snyk; fi"
install:
  - mvn install -DskipTests=true -Dgpg.skip=true
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then snyk test --org=maxmind; fi"
script:
  - mvn javadoc:javadoc
  - mvn test -B
after_success:
  - "if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && $RUN_SNYK && $SNYK_TOKEN ]]; then snyk monitor --org=maxmind --project-name=maxmind/minfraud-api-java; fi"
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "kHsGnfLlzZpzJPlbVLm8jAFWI2qsB2V9DQoFON3hGzHgqj0my2u51OvNj28dcALXqCT9X6TJ450EjQ8lyeaJuzzHTsFU1UB1Z5cb1ObWy0lRx/psgytgxp/nRmBDOdf+ImTHBgO7+szCyTL+YLnyodIv++mgTAxAWxz8e6djryyKHLrqZJnGJ4FzcKPEh/ZfPen+RNUGloj9w0fHzn8ap2Wh24uMfrJsv5Ti/upV3mmrCzK/N7T7h/QYmMEw7h9qcKvKU6p9BH7vE4S1bkhRJfJwO0HQsE6NqrFCP2FvdcUtx0Tkoxedw/QRYpLKU4xGIt1oSljJVD27ADvRwiNin+RmW/MVevMn5AjuJ25GS+FByOswzd9hpswXX6dvV17NffK+pm2T/xlHmV4n8ZZJwRGT2q3YkTaUZ69lPQUCWcJYxs26qn3bWLmaUFCg7L+kACldM1im5QzKjQlFNl2+cfK7dUT/slp6lfSk81Mk0vkDJhin/O+L8RfH4fg2CmTrjdkQCDp/8mw8FBdOW4e6SrWFJmc96jn4+t7rI1hn2zVbCTUoBtlKjIoUNBrsKNsuh4eOiluXimDb09UOG9laoBq9JHDpMkdQtErH3MNID1PGPTuP2UYV/S9sb9fgnl3FuwdFqa7fiw2ITmC59vjWsZAL+IM9c4D4/+9vnUKJ1KE=\n"
